# Generated by Django 5.2.17 on 2026-08-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_test_category_alter_category_options_and_more'),
        ('enrollments', '0002_alter_testenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
